In [1]:
!git clone https://github.com/AbarnaKumarasamy1122/airbnb-data-engineering-assignment.git

Cloning into 'airbnb-data-engineering-assignment'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 19 (delta 1), reused 15 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (19/19), 59.45 KiB | 2.83 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [6]:
%cd /content/airbnb-data-engineering-assignment

/content/airbnb-data-engineering-assignment

In [7]:
import pandas as pd

In [8]:
!git config --global user.name "AbarnaKumarasamy1122"
!git config --global user.email "abarnasamy1122@gmail.com"

In [9]:
!git remote add origin https://github.com/AbarnaKumarasamy1122/airbnb-data-engineering-assignment.git

error: remote origin already exists.

In [10]:
from getpass import getpass
token = getpass('Enter GitHub token: ')

Enter GitHub token: ··········

In [11]:
!git remote set-url origin https://AbarnaKumarasamy1122:$token@github.com/AbarnaKumarasamy1122/airbnb-data-engineering-assignment.git

In [12]:
!git add .
!git commit -m "Updated pipeline from Colab"
!git push -u origin main

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
To https://github.com/AbarnaKumarasamy1122/airbnb-data-engineering-assignment.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/AbarnaKumarasamy1122/airbnb-data-engineering-assignment.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

In [13]:
%%writefile pipelines/ingestion.py

import pandas as pd
import os

class AirbnbIngestion:

    def __init__(self, base_path):
        self.base_path = base_path

    def load_csv(self, filename):
        path = os.path.join(self.base_path, filename)
        if path.endswith(".gz"):
            return pd.read_csv(path, compression="gzip")
        return pd.read_csv(path)

    def ingest_city(self):
        data = {}

        files = [
            "listings.csv.gz",
            "calendar.csv.gz",
            "reviews.csv.gz",
            "neighbourhoods.csv"
        ]

        for file in files:
            key = file.split(".")[0]
            data[key] = self.load_csv(file)

        return data

Overwriting pipelines/ingestion.py

In [25]:
from pipelines.ingestion import AirbnbIngestion

pipeline = AirbnbIngestion("/content/drive/MyDrive/Data Engineer Intern/")
data = pipeline.ingest_city()

listings = data["listings"]
calendar = data["calendar"]
reviews = data["reviews"]
neighbourhoods = data["neighbourhoods"]

In [26]:
%%writefile pipelines/quality_checks.py
import pandas as pd

class DataQuality:

    def missing_report(self, df):
        return (df.isnull().mean() * 100).sort_values(ascending=False)

    def duplicate_check(self, df, subset=None):
        if subset:
            return df.duplicated(subset=subset).sum()
        return df.duplicated().sum()

    def numeric_outliers(self, df, col):
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        return df[(df[col] < lower) | (df[col] > upper)]

Overwriting pipelines/quality_checks.py

In [29]:
from pipelines.quality_checks import DataQuality

dq = DataQuality()

# Assuming 'price' column exists and needs cleaning
if 'price' in listings.columns:
    listings['price_clean'] = listings['price'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)
else:
    print("Warning: 'price' column not found. Skipping price cleaning.")

dq.missing_report(listings).head(10)
dq.duplicate_check(listings, subset=["id"])
dq.numeric_outliers(listings, "price_clean")

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,price_clean
27,68974,https://www.airbnb.com/rooms/68974,20260414135910,2026-04-14,previous scrape,Top floor light filled loft on the Bowery,The loft on the Bowery is a very unique home a...,NaN,https://a0.muscache.com/pictures/airflow/Hosti...,281229,...,4.79,4.66,NaN,NaN,1,1,0,0,1.35,781.70
85,141335,https://www.airbnb.com/rooms/141335,20260414135910,2026-04-14,previous scrape,Architect's Brownstone,Gorgeous duplex brownstone on a quiet tree-li...,NaN,https://a0.muscache.com/pictures/3518019/1aed5...,687361,...,4.88,4.22,NaN,NaN,2,0,2,0,0.24,735.05
109,162493,https://www.airbnb.com/rooms/162493,20260414135910,2026-04-14,previous scrape,Prime Williamsburg 3 BR with Deck,Great duplex apartment in the heart of William...,NaN,https://a0.muscache.com/pictures/100928783/729...,776490,...,4.91,4.96,NaN,NaN,1,0,1,0,0.44,768.87
118,38663,https://www.airbnb.com/rooms/38663,20260414135910,2026-04-14,city scrape,Luxury Brownstone in Boerum Hill,"Beautiful, large home in great hipster neighbo...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,165789,...,4.86,4.62,OSE-STRREG-0001784,NaN,1,0,1,0,0.26,1186.67
128,174966,https://www.airbnb.com/rooms/174966,20260414135910,2026-04-14,previous scrape,Luxury 2Bed/2.5Bath Central Park View,DETAILS: Designer-decorated luxury two bedroo...,NaN,https://a0.muscache.com/pictures/5273916/2bd6e...,836168,...,4.72,4.72,NaN,NaN,10,10,0,0,0.14,2765.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35014,1644748905245383575,https://www.airbnb.com/rooms/1644748905245383575,20260414135910,2026-04-15,city scrape,Studio Suite at Hard Rock Hotel New York!,Located between Radio City Music Hall and the ...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,750439361,...,NaN,NaN,Exempt,NaN,9,0,7,0,NaN,621.10
35015,1644942307359133664,https://www.airbnb.com/rooms/1644942307359133664,20260414135910,2026-04-14,city scrape,The Landmark by Rove Travel | Townhome w/Roof ...,"Welcome to The Landmark, a Rove Travel Home!<b...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,502657573,...,NaN,NaN,Exempt,NaN,46,46,0,0,NaN,2540.00
35022,1645238888151070141,https://www.airbnb.com/rooms/1645238888151070141,20260414135910,2026-04-15,city scrape,2 Deluxe Room at Hard Rock Hotel New York!,Located between Radio City Music Hall and the ...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,750439361,...,NaN,NaN,Exempt,NaN,9,0,7,0,NaN,1031.00
35023,1645252582380140186,https://www.airbnb.com/rooms/1645252582380140186,20260414135910,2026-04-15,city scrape,"Comfort and Convenience! 4 Great Units, Restau...",Located between Radio City Music Hall and the ...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,750439361,...,NaN,NaN,Exempt,NaN,9,0,7,0,NaN,2062.00
35025,1647790197894111714,https://www.airbnb.com/rooms/1647790197894111714,20260414135910,2026-04-14,city scrape,Charming Spacious | 4BED / LIC / Sunnyside,A well-sized two-bedroom apartment in Sunnysid...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,153988027,...,NaN,NaN,OSE-STRREG-0003565,NaN,1,1,0,0,NaN,570.59

In [30]:
%%writefile pipelines/cleaning.py
import pandas as pd
import numpy as np

class AirbnbCleaning:

    def clean_price(self, df):
        df["price_clean"] = (
            df["price"]
            .replace("[$,]", "", regex=True)
            .astype(float)
        )
        return df

    def clean_dates(self, df, cols):
        for c in cols:
            if c in df.columns:
                df[c] = pd.to_datetime(df[c], errors="coerce")
        return df

    def clean_text(self, df, cols):
        for c in cols:
            if c in df.columns:
                df[c] = df[c].str.lower().str.strip()
        return df

Overwriting pipelines/cleaning.py

In [32]:
from pipelines.cleaning import AirbnbCleaning

cleaner = AirbnbCleaning()

listings = cleaner.clean_price(listings)
listings = cleaner.clean_dates(listings, ["host_since", "first_review", "last_review"])
listings = cleaner.clean_text(listings, ["room_type", "property_type"])

In [33]:
%%writefile pipelines/transformations.py
import pandas as pd

class AirbnbTransform:

    def compute_host_tenure(self, df):
        df["host_since"] = pd.to_datetime(df["host_since"])
        df["host_tenure_years"] = (
            (pd.Timestamp("today") - df["host_since"]).dt.days / 365
        )
        return df

    def price_per_bedroom(self, df):
        df["price_per_bedroom"] = df["price_clean"] / df["bedrooms"]
        return df

    def occupancy_rate(self, calendar):
        summary = calendar.groupby("listing_id")["available"].apply(
            lambda x: (x == "f").mean()
        )
        return summary.reset_index(name="occupancy_rate")

Overwriting pipelines/transformations.py

In [35]:
from pipelines.transformations import AirbnbTransform

transform = AirbnbTransform()

listings = transform.compute_host_tenure(listings)
listings = transform.price_per_bedroom(listings)

In [36]:
reviews_summary = reviews.groupby("listing_id").size().reset_index(name="review_count")

master = listings.merge(
    reviews_summary,
    left_on="id",
    right_on="listing_id",
    how="left"
)

In [37]:
calendar["available_flag"] = calendar["available"].map({"t": 1, "f": 0})

occupancy = calendar.groupby("listing_id")["available_flag"].mean().reset_index()
occupancy.columns = ["id", "occupancy_rate"]

master = master.merge(occupancy, on="id", how="left")

In [38]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)

In [39]:
import duckdb

con = duckdb.connect("airbnb.duckdb")

In [40]:
con.execute("CREATE TABLE listings AS SELECT * FROM master")
con.execute("CREATE TABLE calendar AS SELECT * FROM calendar")
con.execute("CREATE TABLE reviews AS SELECT * FROM reviews")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [41]:
con.execute("""
SELECT neighbourhood, AVG(price_clean)
FROM listings
GROUP BY neighbourhood
ORDER BY AVG(price_clean) DESC
""").df()

   neighbourhood  avg(price_clean)
0            NaN        254.998857

In [42]:
def run_pipeline(base_path):

    ingestion = AirbnbIngestion(base_path)
    data = ingestion.ingest_city()

    cleaner = AirbnbCleaning()
    transform = AirbnbTransform()

    listings = cleaner.clean_price(data["listings"])
    listings = transform.compute_host_tenure(listings)

    return listings